import React, { Suspense, useDeferredValue, useEffect, useId, useMemo, useRef, useState } from 'react';
import { Download, Maximize2, RotateCcw, SlidersHorizontal, X } from 'lucide-react';
import { graphPoints, chartAllowed, exactLabel, plotCsv, type VisualDataset, type VisualSettings, type VisualKind, type VisualPoint } from '../../lib/visuals/model';
import { categoryColour } from '../../lib/visuals/palette';
const VisualPlot=React.lazy(()=>import('./VisualPlot'));
const kinds:[VisualKind,string][]=[['bar','Horizontal bars'],['column','Columns'],['line','Line'],['area','Area'],['scatter','Scatter'],['heatmap','Heatmap'],['donut','Doughnut']];
const save=(text:string,name:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export default function VisualExplorer({datasets,onInspect}:{datasets:VisualDataset[];onInspect?:(dataset:VisualDataset,rowIndex:number)=>void}){
  const [chosen,setChosen]=useState('');const dataset=datasets.find(d=>d.id===chosen)||datasets[0];
  if(!dataset)return <div className="cx-viz-empty" role="status">No returned data is available to visualise. No sample figures are substituted.</div>;
  return <div className="cx-visual-explorer" data-visual-id={dataset.id}>
    {datasets.length>1&&<label className="cx-viz-dataset"><span>Dataset to visualise</span><select aria-label="Dataset to visualise" value={dataset.id} onChange={e=>setChosen(e.target.value)}>{datasets.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><small>{datasets.length} datasets from this response</small></label>}
    <div key={dataset.id}><PlotControls dataset={dataset} onInspect={onInspect}/></div>
  </div>;
}
function PlotControls({dataset,onInspect}:{dataset:VisualDataset;onInspect?:(dataset:VisualDataset,rowIndex:number)=>void}){
  const initial=():VisualSettings=>({dimension:dataset.defaultDimension||dataset.dimensions[0]?.key||'',measure:dataset.defaultMeasure||dataset.measures[0]?.key||'',compare:'',mode:dataset.measures.length?'values':'records',search:'',sort:dataset.dimensions[0]?.ordered?'label':'source',offset:0,limit:25});
  const [settings,setSettings]=useState<VisualSettings>(initial),[kind,setKind]=useState<VisualKind>(dataset.dimensions[0]?.ordered?'line':'bar');
  const [height,setHeight]=useState(320),[inspectKey,setInspectKey]=useState<string|null>(null),[notice,setNotice]=useState(''),[advanced,setAdvanced]=useState(false);
  useEffect(()=>{setInspectKey(null);setSettings(old=>old.offset?{...old,offset:0}:old);},[dataset.rows]);
  const deferredSearch=useDeferredValue(settings.search),root=useRef<HTMLDivElement>(null),uid=useId();
  const inspectTrigger=useRef<HTMLElement|null>(null);
  const view=useMemo(()=>graphPoints(dataset,{...settings,search:deferredSearch,separateAxes:kind==='scatter'}),[dataset,settings,deferredSearch,kind]);
  const allowed=chartAllowed(kind,view.dimension,view.mode,!!view.comparison),renderKind=allowed?kind:'bar';
  const change=(patch:Partial<VisualSettings>)=>{setSettings(old=>({...old,...patch,offset:patch.offset??0}));setInspectKey(null);};
  const chooseKind=(next:VisualKind)=>{setKind(next);if(next==='line'||next==='area')change({sort:'label'});if(next==='scatter'&&!settings.compare)change({compare:dataset.measures.find(m=>m.key!==view.metric.key)?.key||''});};
  const selected=view.points.find(p=>p.key===inspectKey),updating=deferredSearch!==settings.search;
  const reset=()=>{setSettings(initial());setKind(dataset.dimensions[0]?.ordered?'line':'bar');setHeight(320);setInspectKey(null);setNotice('');};
  const fullname=dataset.id.replace(/[^\w-]+/g,'-').slice(0,80);
  const image=()=>{const svg=root.current?.querySelector('.cx-viz-canvas svg');if(!svg){setNotice('SVG export is available for the chart types rendered with SVG.');return;}const clone=svg.cloneNode(true) as SVGSVGElement;clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('style','background:white;font-family:Arial,sans-serif');save(new XMLSerializer().serializeToString(clone),`cx-${fullname}.svg`,'image/svg+xml');setNotice('Exported the displayed chart. Values in the exact CSV are unchanged.');};
  const fullscreen=async()=>{try{if(document.fullscreenElement===root.current)await document.exitFullscreen();else await root.current?.requestFullscreen();}catch{setNotice('Full-screen mode is unavailable in this browser.');}};
  const click=(point:VisualPoint)=>{inspectTrigger.current=document.activeElement as HTMLElement|null;setInspectKey(point.key);};
  const closeInspection=()=>{setInspectKey(null);inspectTrigger.current?.focus({preventScroll:true});};
  const exportPoints=(scope:'displayed'|'matching'|'loaded')=>{
    const exported=scope==='loaded'?graphPoints(dataset,{...settings,search:'',separateAxes:kind==='scatter'}):view;
    const points=scope==='displayed'?view.points:exported.all;
    save(plotCsv(points,exported.metric,exported.comparison,dataset),`cx-${fullname}-${scope}.csv`,'text/csv;charset=utf-8');
    setNotice(`Exported ${points.length} ${scope} ${view.mode==='records'?'category counts':'points'} from the loaded response. API limits still apply.`);
  };
  return <section ref={root} className="cx-viz" aria-label={`Visual view: ${dataset.title}`} data-testid="visual-view">
    <header className="cx-viz-heading"><div><h3>{dataset.title}</h3><p>{dataset.note}</p></div><div className="cx-viz-actions"><button type="button" aria-label="Reset chart" title="Reset chart" onClick={reset}><RotateCcw size={16}/></button><button type="button" aria-label="Full screen chart" title="Full screen" onClick={fullscreen}><Maximize2 size={16}/></button></div></header>
    <div className="cx-viz-controls">
      <label><span>Chart type</span><select aria-label="Chart type" value={renderKind} onChange={e=>chooseKind(e.target.value as VisualKind)}>{kinds.map(([id,label])=><option key={id} value={id} disabled={!chartAllowed(id,view.dimension,view.mode,!!view.comparison)&&!(id==='scatter'&&view.mode==='values'&&dataset.measures.length>1)}>{label}</option>)}</select></label>
      <label><span>Plot</span><select aria-label="Plot mode" value={view.mode} onChange={e=>change({mode:e.target.value as any,compare:''})}><option value="values" disabled={!dataset.measures.length}>Returned metric values</option><option value="records">Returned record distribution</option></select></label>
      <label><span>{view.mode==='records'?'Group returned records by':'Label points by'}</span><select aria-label="Chart dimension" value={view.dimension?.key||''} onChange={e=>change({dimension:e.target.value})}>{!dataset.dimensions.length&&<option value="">Returned row order</option>}{dataset.dimensions.map(d=><option key={d.key} value={d.key}>{d.label}</option>)}</select></label>
      <label><span>Measure</span><select aria-label="Chart measure" value={settings.measure} disabled={view.mode==='records'} onChange={e=>change({measure:e.target.value,compare:''})}>{!dataset.measures.length&&<option value="">Returned Record Count</option>}{dataset.measures.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label>
    </div>
    <div className="cx-viz-tools"><label><span>Search chart labels</span><input type="search" aria-label="Search chart labels" maxLength={200} value={settings.search} placeholder="Find a category or date…" onChange={e=>change({search:e.target.value})}/></label><button type="button" aria-expanded={advanced} aria-controls={uid} onClick={()=>setAdvanced(v=>!v)}><SlidersHorizontal size={14}/>Adjust chart</button><button type="button" disabled={updating||!view.points.length} onClick={()=>exportPoints('displayed')}><Download size={14}/>Exact displayed CSV</button></div>
    {advanced&&<div id={uid} className="cx-viz-controls cx-viz-advanced">
      <label><span>{renderKind==='scatter'?'X-axis measure':'Compare series (same unit)'}</span><select aria-label="Compare series" disabled={view.mode==='records'} value={view.comparison?.key||''} onChange={e=>change({compare:e.target.value})}><option value="">No comparison</option>{dataset.measures.filter(m=>m.key!==view.metric.key&&(renderKind==='scatter'||m.unit===view.metric.unit)).map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label>
      <label><span>Order</span><select aria-label="Chart sort" value={settings.sort} disabled={renderKind==='line'||renderKind==='area'} onChange={e=>change({sort:e.target.value as any})}><option value="source">API row order</option><option value="label">Label / chronological order</option><option value="descending">Value: highest first</option><option value="ascending">Value: lowest first</option></select></label>
      <label><span>Points per view</span><select aria-label="Chart point limit" value={settings.limit} onChange={e=>change({limit:Number(e.target.value)})}>{[10,25,50,100,250].map(v=><option value={v} key={v}>{v}</option>)}</select></label>
      <label><span>Chart height</span><select aria-label="Chart height" value={height} onChange={e=>setHeight(Number(e.target.value))}>{[240,320,480,640].map(v=><option value={v} key={v}>{v} px</option>)}</select></label>
    </div>}
    <div className="cx-viz-caption" role="status" aria-live="polite">{updating?'Updating chart…':`Showing ${view.total?view.offset+1:0}–${Math.min(view.offset+view.limit,view.total)} of ${view.total} ${view.mode==='records'?'category counts':'returned points'}.`} {view.excluded>0&&`${view.excluded} missing or invalid values remain gaps.`}</div>
    <p className="cx-viz-axis-note">{renderKind==='scatter'?`X: ${view.comparison?.label}. Y: ${view.metric.label}.`:`Measure: ${view.metric.label}.`} {view.mode==='records'?'Counts describe returned records, not unique people or events.':'Each point is a returned row. Duplicate labels are not merged.'} {renderKind==='donut'&&'Shares apply only to displayed categories.'} Selecting a mark opens exact values; it does not filter the report.</p>
    <p className="cx-viz-caption">{dataset.rows.length.toLocaleString('en-GB')} loaded rows. Chart settings and search are local display controls. {view.mode==='records'&&'Measure and comparison are unavailable in record-distribution mode.'} Lines and areas require an ordered dimension; doughnuts require returned-record counts.</p>
    {view.imprecise&&<p className="cx-viz-warning">Plot positions use approximate numeric coordinates. Exact decimal values are retained in point details and the CSV; very close large values may look identical.</p>}
    {!dataset.rows.length?<div className="cx-viz-empty" role="status">No rows were returned. This is not a measured zero.</div>:<div aria-busy={updating} className={updating?'cx-viz-updating':''}><Suspense fallback={<div className="cx-viz-empty" role="status">Loading chart renderer…</div>}><VisualPlot points={view.points} kind={renderKind} metric={view.metric} comparison={view.comparison} height={renderKind==='bar'?Math.max(height,Math.min(view.points.length*28+60,720)):height} onInspect={click}/></Suspense></div>}
    {view.total>settings.limit&&<div className="cx-viz-window"><button type="button" aria-label="Previous chart points" disabled={!view.offset} onClick={()=>change({offset:Math.max(0,view.offset-view.limit)})}>Previous</button><label><span>Chart window</span><input type="range" aria-label="Chart window" min={0} max={Math.max(0,view.total-view.limit)} value={view.offset} onChange={e=>change({offset:Number(e.target.value)})}/></label><button type="button" aria-label="Next chart points" disabled={view.offset+view.limit>=view.total} onClick={()=>change({offset:view.offset+view.limit})}>Next</button></div>}
    {renderKind==='donut'&&<ul className="cx-viz-legend" aria-label="Displayed category legend">{view.points.map(p=><li key={p.key}><span aria-hidden="true" style={{background:categoryColour(p.label,p.categoryKey)}}/><span>{p.label}</span><strong>{exactLabel(p.exact)}</strong></li>)}</ul>}
    <details className="cx-viz-exact"><summary>Inspect exact plotted values ({view.points.length})</summary><p>Keyboard-accessible point selection. Chart-only search and windows do not change the original report or its loaded export.</p><div className="cx-viz-point-list">{view.points.map(p=><button type="button" key={p.key} aria-pressed={p.key===inspectKey} onClick={()=>click(p)}><span>{p.label}</span><span>{exactLabel(p.exact)}{view.comparison&&<small>{view.comparison.label}: {exactLabel(p.compareExact)}</small>}</span></button>)}</div></details>
    {selected&&<aside className="cx-viz-inspect" aria-label="Selected chart point"><button type="button" aria-label="Close chart point" onClick={closeInspection}><X size={15}/></button><strong>{selected.label}</strong><p>{view.metric.label}: {exactLabel(selected.exact)}</p>{view.comparison&&<p>{view.comparison.label}: {exactLabel(selected.compareExact)}</p>}{onInspect&&selected.rowIndex!==null&&<button type="button" onClick={()=>onInspect(dataset,selected.rowIndex!)}>Open supporting records</button>}</aside>}
    <details className="cx-viz-exports"><summary>More export options</summary><p>Matching exports include local search results across every chart window. Loaded exports ignore local search. Neither requests additional warehouse data.</p><div className="cx-viz-tools"><button type="button" disabled={updating||!view.total} onClick={()=>exportPoints('matching')}>Export matching points CSV</button><button type="button" disabled={!dataset.rows.length} onClick={()=>exportPoints('loaded')}>Export all loaded points CSV</button><button type="button" onClick={image}>Export SVG</button></div></details>
    {notice&&<p role="status" className="cx-viz-caption">{notice}</p>}
  </section>;
}
