import React, { useMemo, useState } from 'react';
import { BrowserRouter, Link, useLocation } from 'react-router-dom';
import { Activity, ArrowRight, BarChart3, ChevronLeft, ChevronRight, Database, FlaskConical, LayoutDashboard, ListFilter, Phone, Search, Settings2, ShieldCheck, Users, X } from 'lucide-react';
import Modal from '../components/Modal';
import DemoTable from '../components/visuals/DemoTable';
import { LIVE_ENTRY_URL } from '../lib/applicationMode';
import { DEMO_LEADS, DEMO_SCENARIO, filterDemoLeads, groupDemoLeads, summariseDemoLeads, type DemoLead } from '../lib/demoData';
import '../styles/demo.css';

const PAGES = [
  { path: '/overview', title: 'Overview', icon: LayoutDashboard, description: 'A complete picture of a fictional July campaign, from captured lead to activation.' },
  { path: '/vendors', title: 'Vendor Performance', icon: Users, description: 'Compare fictional vendors using one consistent, filtered sample population.' },
  { path: '/leads', title: 'Lead Records', icon: Database, description: 'Search, sort and inspect individual synthetic records. Nothing here identifies a real customer.' },
  { path: '/call-performance', title: 'Call Performance', icon: Phone, description: 'Explore example calling activity and first-dial timing in the selected sample.' },
  { path: '/data-quality', title: 'Data Quality', icon: ShieldCheck, description: 'Inspect the shape and completeness of the demo rows—not the quality of your live warehouse.' },
  { path: '/settings', title: 'Configuration', icon: Settings2, description: 'Understand the clear boundary between this local demonstration and authenticated live reporting.' },
];
const VENDORS = [...new Set(DEMO_LEADS.map(row => row.vendor))].sort();
const SOURCES = [...new Set(DEMO_LEADS.map(row => row.source))].sort();
const STATUSES: DemoLead['status'][] = ['New', 'Contacted', 'Qualified', 'Sale', 'Activated'];
const initialFilters = { startDate: DEMO_SCENARIO.startDate, endDate: DEMO_SCENARIO.endDate, vendor: '', source: '', status: '', search: '' };
const number = (value: number) => value.toLocaleString('en-GB');
const money = (cents: number) => `ZAR ${(cents / 100).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const percent = (value: number) => `${value.toFixed(2)}%`;
const date = (value: string) => new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', timeZone: 'UTC' });
type Group = ReturnType<typeof groupDemoLeads>[number];

function Metric({ label, value, note }: { label: string; value: string; note: string }) {
  return <article className="cx-demo-metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;
}

function GroupChart({ title, groups, onSelect }: { title: string; groups: Group[]; onSelect: (name: string) => void }) {
  const [measure, setMeasure] = useState<'leads' | 'sales' | 'activations' | 'revenueCents'>('leads');
  const maximum = Math.max(0, ...groups.map(group => group[measure]));
  const label = measure === 'revenueCents' ? 'Illustrative value' : measure === 'sales' ? 'Sales' : measure === 'activations' ? 'Activations' : 'Leads';
  return <section className="cx-demo-card"><header><div><h2>{title}</h2><p>Select a bar to filter the whole demo.</p></div><label className="cx-demo-measure"><span className="sr-only">{title} measure</span><select aria-label={`${title} measure`} value={measure} onChange={event => setMeasure(event.target.value as typeof measure)}><option value="leads">Leads</option><option value="sales">Sales</option><option value="activations">Activations</option><option value="revenueCents">Illustrative value</option></select></label></header>
    {groups.length ? <div className="cx-demo-bars">{[...groups].sort((a, b) => b[measure] - a[measure]).map(group => <button key={group.name} type="button" onClick={() => onSelect(group.name)} aria-label={`Filter by ${group.name}: ${measure === 'revenueCents' ? money(group[measure]) : number(group[measure])} ${label.toLowerCase()}`}><span>{group.name}</span><span className="cx-demo-bar-track" aria-hidden="true"><i style={{ width: `${maximum ? group[measure] / maximum * 100 : 0}%` }} /></span><strong>{measure === 'revenueCents' ? money(group[measure]) : number(group[measure])}</strong></button>)}</div> : <p className="cx-demo-empty">No groups match the current filters.</p>}
  </section>;
}

function RecordTable({ rows, onInspect }: { rows: readonly DemoLead[]; onInspect: (lead: DemoLead) => void }) {
  return <div className="cx-demo-table-scroll" role="region" aria-label="Scrollable synthetic lead records" tabIndex={0}><DemoTable className="cx-demo-table" label="Synthetic demo records"><caption className="sr-only">Synthetic lead records. All monetary values and identities are fictional.</caption><thead><tr><th scope="col">Lead ID</th><th scope="col">Vendor</th><th scope="col">Source</th><th scope="col">Captured · UTC</th><th scope="col">Status</th><th scope="col">Calls</th><th scope="col">Illustrative value</th><th scope="col">Details</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><th scope="row">{row.id}</th><td>{row.vendor}</td><td>{row.source}</td><td>{date(row.capturedAt)}</td><td><span className="cx-demo-status" data-status={row.status}>{row.status}</span></td><td>{number(row.callAttempts)}</td><td>{money(row.revenueCents)}</td><td><button className="cx-link-button" type="button" onClick={() => onInspect(row)} aria-label={`Inspect demo lead ${row.id}`}>Inspect <ArrowRight size={13} aria-hidden="true" /></button></td></tr>)}</tbody></DemoTable></div>;
}

function DemoContent() {
  const location = useLocation();
  const current = PAGES.find(page => page.path === location.pathname) ?? PAGES[0];
  const [filters, setFilters] = useState(initialFilters);
  const [sort, setSort] = useState('newest'), [page, setPage] = useState(0);
  const [selected, setSelected] = useState<DemoLead | null>(null);
  const changeFilter = (key: keyof typeof filters, value: string) => { setFilters(old => ({ ...old, [key]: value })); setPage(0); setSelected(null); };
  const reset = () => { setFilters(initialFilters); setPage(0); setSort('newest'); setSelected(null); };
  const invalidDates = !filters.startDate || !filters.endDate || filters.startDate > filters.endDate || filters.startDate < DEMO_SCENARIO.startDate || filters.endDate > DEMO_SCENARIO.endDate;
  const rows = useMemo(() => invalidDates ? [] : filterDemoLeads({ ...filters, status: filters.status as DemoLead['status'] | '' }), [filters, invalidDates]);
  const summary = useMemo(() => summariseDemoLeads(rows), [rows]);
  const vendors = useMemo(() => groupDemoLeads(rows, 'vendor'), [rows]);
  const sources = useMemo(() => groupDemoLeads(rows, 'source'), [rows]);
  const sorted = useMemo(() => [...rows].sort((a, b) => sort === 'oldest' ? a.capturedAt.localeCompare(b.capturedAt) || a.id.localeCompare(b.id) : sort === 'value' ? b.revenueCents - a.revenueCents || a.id.localeCompare(b.id) : sort === 'calls' ? b.callAttempts - a.callAttempts || a.id.localeCompare(b.id) : b.capturedAt.localeCompare(a.capturedAt) || a.id.localeCompare(b.id)), [rows, sort]);
  const pageCount = Math.max(1, Math.ceil(sorted.length / 10)), safePage = Math.min(page, pageCount - 1), pageRows = sorted.slice(safePage * 10, safePage * 10 + 10);
  const stageCounts = [['Captured leads', summary.leads], ['Contacted or later', summary.contacted], ['Qualified or later', rows.filter(row => ['Qualified', 'Sale', 'Activated'].includes(row.status)).length], ['Sale or activated', summary.sales], ['Activated', summary.activations]] as const;
  const weekly = useMemo(() => Array.from({ length: 5 }, (_, index) => ({ label: `${index * 7 + 1}–${Math.min(31, index * 7 + 7)} Jul`, value: rows.filter(row => Math.floor((Number(row.capturedAt.slice(8, 10)) - 1) / 7) === index).length })), [rows]);
  const weeklyMax = Math.max(1, ...weekly.map(week => week.value));
  const called = rows.filter(row => row.callAttempts > 0);
  const timings = rows.flatMap(row => row.firstDialMinutes === null ? [] : [row.firstDialMinutes]).sort((a, b) => a - b);
  const medianDial = timings.length ? (timings[Math.floor((timings.length - 1) / 2)] + timings[Math.floor(timings.length / 2)]) / 2 : null;
  const callBands = [{ label: 'No call', count: rows.filter(row => row.callAttempts === 0).length }, { label: '1 call', count: rows.filter(row => row.callAttempts === 1).length }, { label: '2–3 calls', count: rows.filter(row => row.callAttempts >= 2 && row.callAttempts <= 3).length }, { label: '4+ calls', count: rows.filter(row => row.callAttempts >= 4).length }];
  const quality = [
    { label: 'Duplicate sample IDs', value: rows.length - new Set(rows.map(row => row.id)).size, note: 'Each synthetic row should have one unique identifier.' },
    { label: 'Missing vendor or source', value: rows.filter(row => !row.vendor || !row.source).length, note: 'Local grouping fields—not a review of production mappings.' },
    { label: 'Invalid capture timestamps', value: rows.filter(row => !Number.isFinite(Date.parse(row.capturedAt))).length, note: 'Capture dates are parsed from the fixed July scenario.' },
    { label: 'Invalid call counts', value: rows.filter(row => !Number.isInteger(row.callAttempts) || row.callAttempts < 0).length, note: 'Sample attempt counts must be non-negative whole numbers.' },
    { label: 'Records without first-dial timing', value: rows.filter(row => row.firstDialMinutes === null).length, note: 'Intentionally includes undialled examples. Missing timing is not zero minutes.' },
  ];
  const unsupportedRoute = !PAGES.some(item => item.path === location.pathname) && !['/', '/reports'].includes(location.pathname);
  const clearActive = Object.entries(filters).some(([key, value]) => value !== initialFilters[key as keyof typeof filters]);

  return <div className="cx-demo-app">
    <a className="cx-demo-skip" href="#demo-main">Skip to demo content</a>
    <aside className="cx-demo-sidebar"><div className="cx-demo-brand"><span><Activity size={23} aria-hidden="true" /></span><div><strong>ConversionX</strong><small>Lead & revenue analytics</small></div></div><div className="cx-demo-nav-heading">Explore the demo</div><nav aria-label="Demo workspace navigation">{PAGES.map(item => <Link key={item.path} to={`${item.path}?mode=demo`} aria-current={current.path === item.path ? 'page' : undefined}><item.icon size={18} aria-hidden="true" /><span>{item.title}</span></Link>)}</nav><div className="cx-demo-sidebar-note"><FlaskConical size={19} aria-hidden="true" /><strong>Safe to explore</strong><p>Fictional records only. Filters stay in this browser session and never change live data.</p><span>July 2026 · ZAR · UTC</span></div></aside>
    <div className="cx-demo-workarea"><div className="cx-demo-banner" role="note"><FlaskConical size={18} aria-hidden="true" /><div><strong>Synthetic demo data — no live connection</strong><span>Explore safely while live authentication is configured.</span></div><a href={LIVE_ENTRY_URL}>Open live mode <ArrowRight size={15} aria-hidden="true" /></a></div>
      <main id="demo-main" className="cx-demo-main" tabIndex={-1}><header className="cx-demo-page-heading"><div><span className="cx-demo-eyebrow">ConversionX / Interactive demonstration</span><h1>{current.title}</h1><p>{current.description}</p></div><span className="cx-demo-scenario"><FlaskConical size={15} aria-hidden="true" />July 2026 scenario</span></header>
        {unsupportedRoute && <p className="cx-demo-route-note">This route is not part of the six demo sections. Showing the demo Overview; use the navigation to explore the available sample workflows.</p>}
        {current.path !== '/settings' && <>
          <section className="cx-demo-card cx-demo-filters" aria-label="Demo data filters"><header><div><h2><ListFilter size={17} aria-hidden="true" />Filter the sample</h2><p>Every total, chart and table below uses the same selected rows.</p></div><button className="cx-button-secondary" type="button" onClick={reset} disabled={!clearActive && sort === 'newest'}>Reset demo filters</button></header><div className="cx-demo-filter-grid">
            <label>From · UTC<input aria-label="Demo start date" type="date" min={DEMO_SCENARIO.startDate} max={DEMO_SCENARIO.endDate} value={filters.startDate} onChange={event => changeFilter('startDate', event.target.value)} /></label>
            <label>Through · UTC<input aria-label="Demo end date" type="date" min={DEMO_SCENARIO.startDate} max={DEMO_SCENARIO.endDate} value={filters.endDate} onChange={event => changeFilter('endDate', event.target.value)} /></label>
            <label>Vendor<select aria-label="Demo vendor" value={filters.vendor} onChange={event => changeFilter('vendor', event.target.value)}><option value="">All demo vendors</option>{VENDORS.map(value => <option key={value}>{value}</option>)}</select></label>
            <label>Source<select aria-label="Demo source" value={filters.source} onChange={event => changeFilter('source', event.target.value)}><option value="">All demo sources</option>{SOURCES.map(value => <option key={value}>{value}</option>)}</select></label>
            <label>Lifecycle status<select aria-label="Demo lifecycle status" value={filters.status} onChange={event => changeFilter('status', event.target.value)}><option value="">All sample statuses</option>{STATUSES.map(value => <option key={value}>{value}</option>)}</select></label>
            <label className="cx-demo-search">Search records<span><Search size={16} aria-hidden="true" /><input aria-label="Search demo records" type="search" value={filters.search} onChange={event => changeFilter('search', event.target.value)} placeholder="Lead ID, vendor or source" /></span></label>
          </div><p className="cx-demo-scope" role="status" aria-live="polite">{invalidDates ? 'Choose a valid date range within 1–31 July 2026.' : `${number(rows.length)} of ${number(DEMO_LEADS.length)} synthetic records selected · ${date(filters.startDate)}–${date(filters.endDate)} 2026 · UTC`}</p></section>
          {!rows.length && <section className="cx-demo-card cx-demo-empty-state" aria-label="No matching demo records"><Search size={24} aria-hidden="true" /><h2>No sample records match</h2><p>Try a different vendor, source, date or search. Live data is never substituted.</p><button className="cx-button-primary" type="button" onClick={reset}>Reset filters and show all demo data</button></section>}
        </>}
        {current.path === '/overview' && <>
          <div className="cx-demo-metrics" aria-label="Demo overview metrics"><Metric label="Captured leads" value={number(summary.leads)} note="Selected synthetic records" /><Metric label="Recorded sales" value={number(summary.sales)} note={`${percent(summary.conversionRate)} of selected leads`} /><Metric label="Activations" value={number(summary.activations)} note={`${percent(summary.activationRate)} of selected leads`} /><Metric label="Call attempts" value={number(summary.callAttempts)} note="Sum of sample attempt counts" /><Metric label="Illustrative value" value={money(summary.revenueCents)} note="Fictional amounts—not live revenue" /></div>
          <div className="cx-demo-two-columns"><section className="cx-demo-card"><header><div><h2>From interest to activation</h2><p>Cumulative lifecycle stages within the selected sample.</p></div><BarChart3 size={20} aria-hidden="true" /></header><ol className="cx-demo-funnel">{stageCounts.map(([label, count], index) => <li key={label}><span>{index + 1}</span><div><div><strong>{label}</strong><b>{number(count)}</b></div><i aria-hidden="true"><em style={{ width: `${summary.leads ? count / summary.leads * 100 : 0}%` }} /></i></div></li>)}</ol><p className="cx-demo-footnote">Sales includes activated records. These overlapping stages must not be added together.</p></section>
          <section className="cx-demo-card"><header><div><h2>Capture rhythm</h2><p>Selected leads grouped into July calendar weeks.</p></div></header><ol className="cx-demo-weekly">{weekly.map(week => <li key={week.label}><strong>{number(week.value)}</strong><span className="cx-demo-week-track" aria-hidden="true"><i style={{ height: `${week.value / weeklyMax * 100}%` }} /></span><small>{week.label}</small></li>)}</ol><p className="cx-demo-footnote">Fixed synthetic scenario. No historical or forecast claim is made.</p></section></div>
          <div className="cx-demo-two-columns"><GroupChart title="Vendor contribution" groups={vendors} onSelect={name => changeFilter('vendor', name)} /><GroupChart title="Source mix" groups={sources} onSelect={name => changeFilter('source', name)} /></div>
          <section className="cx-demo-card cx-demo-record-card"><header><div><h2>Recently captured sample leads</h2><p>Inspect a row to see its fictional attributes.</p></div><Link className="cx-link-button" to="/leads?mode=demo">All lead records <ArrowRight size={14} aria-hidden="true" /></Link></header>{rows.length > 0 && <RecordTable rows={sorted.slice(0, 5)} onInspect={setSelected} />}</section>
        </>}
        {current.path === '/vendors' && <><div className="cx-demo-metrics cx-demo-metrics-four"><Metric label="Selected vendors" value={number(vendors.length)} note="Distinct fictional vendor labels" /><Metric label="Captured leads" value={number(summary.leads)} note="One sample row per lead" /><Metric label="Sales / leads" value={percent(summary.conversionRate)} note="Includes activated sales" /><Metric label="Illustrative value" value={money(summary.revenueCents)} note="Not live or collected revenue" /></div><div className="cx-demo-two-columns"><GroupChart title="Vendor comparison" groups={vendors} onSelect={name => changeFilter('vendor', name)} /><GroupChart title="Source mix" groups={sources} onSelect={name => changeFilter('source', name)} /></div><section className="cx-demo-card cx-demo-record-card"><header><div><h2>Vendor comparison table</h2><p>Click a vendor to apply the same filter to all demo sections.</p></div></header><div className="cx-demo-table-scroll" role="region" aria-label="Scrollable demo vendor comparison" tabIndex={0}><DemoTable className="cx-demo-table" label="Synthetic demo records"><thead><tr>{['Vendor', 'Leads', 'Contacted', 'Sales', 'Activations', 'Sales / leads', 'Illustrative value'].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{vendors.map(group => <tr key={group.name}><th scope="row"><button className="cx-link-button" type="button" onClick={() => changeFilter('vendor', group.name)}>{group.name}</button></th><td>{number(group.leads)}</td><td>{number(group.contacted)}</td><td>{number(group.sales)}</td><td>{number(group.activations)}</td><td>{percent(group.conversionRate)}</td><td>{money(group.revenueCents)}</td></tr>)}</tbody></DemoTable></div></section></>}
        {current.path === '/leads' && <section className="cx-demo-card cx-demo-record-card"><header><div><h2>Sample record explorer</h2><p>Ten records per page. Search above filters the entire demo, not only this page.</p></div><label className="cx-demo-measure">Sort records<select aria-label="Sort demo records" value={sort} onChange={event => { setSort(event.target.value); setPage(0); }}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="value">Highest illustrative value</option><option value="calls">Most call attempts</option></select></label></header>{rows.length > 0 && <RecordTable rows={pageRows} onInspect={setSelected} />}<footer className="cx-demo-pagination"><span role="status">Showing {rows.length ? safePage * 10 + 1 : 0}–{Math.min((safePage + 1) * 10, rows.length)} of {number(rows.length)} sample records</span><div><button className="cx-button-secondary" type="button" disabled={safePage === 0} onClick={() => setPage(old => Math.max(0, old - 1))}><ChevronLeft size={16} aria-hidden="true" />Previous</button><span>Page {safePage + 1} of {pageCount}</span><button className="cx-button-secondary" type="button" disabled={safePage + 1 >= pageCount} onClick={() => setPage(old => old + 1)}>Next<ChevronRight size={16} aria-hidden="true" /></button></div></footer></section>}
        {current.path === '/call-performance' && <><div className="cx-demo-metrics cx-demo-metrics-four"><Metric label="Call attempts" value={number(summary.callAttempts)} note="Sum of sample attempt counts" /><Metric label="Leads with a call" value={number(called.length)} note="At least one synthetic attempt" /><Metric label="Attempts per called lead" value={called.length ? (summary.callAttempts / called.length).toFixed(2) : 'Unavailable'} note="Attempts divided by called leads" /><Metric label="Median first dial" value={medianDial === null ? 'Unavailable' : `${number(medianDial)} min`} note={`${number(timings.length)} sample timing values`} /></div><div className="cx-demo-two-columns"><section className="cx-demo-card"><header><div><h2>Call-attempt distribution</h2><p>Mutually exclusive bands across the selected sample.</p></div></header><div className="cx-demo-call-bands">{callBands.map(band => <article key={band.label}><span>{band.label}</span><strong>{number(band.count)}</strong><small>{summary.leads ? percent(band.count / summary.leads * 100) : '0.00%'} of selected leads</small></article>)}</div><p className="cx-demo-footnote">Calls are example attempt counts. RPC or contact success is not inferred from a call or a sale.</p></section><section className="cx-demo-card"><header><div><h2>Example first-dial timing</h2><p>Null timing is retained as missing, never converted to zero.</p></div></header><dl className="cx-demo-detail-list"><div><dt>Within 5 minutes</dt><dd>{number(timings.filter(value => value <= 5).length)}</dd></div><div><dt>6–30 minutes</dt><dd>{number(timings.filter(value => value > 5 && value <= 30).length)}</dd></div><div><dt>More than 30 minutes</dt><dd>{number(timings.filter(value => value > 30).length)}</dd></div><div><dt>No timing value</dt><dd>{number(rows.length - timings.length)}</dd></div></dl></section></div></>}
        {current.path === '/data-quality' && <><section className="cx-demo-card cx-demo-quality-note"><ShieldCheck size={25} aria-hidden="true" /><div><h2>Sample integrity, not warehouse validation</h2><p>These counts inspect only the {number(rows.length)} selected fictional records bundled with this app. They do not certify Google Cloud tables, source freshness or production accuracy.</p></div></section><section className="cx-demo-card cx-demo-record-card"><header><div><h2>Local sample checks</h2><p>Computed in your browser from the same filtered rows.</p></div></header><div className="cx-demo-quality-list">{quality.map(check => <article key={check.label}><div><h3>{check.label}</h3><p>{check.note}</p></div><strong>{number(check.value)}</strong></article>)}</div></section><div className="cx-demo-two-columns"><section className="cx-demo-card"><header><h2>Included in this demonstration</h2></header><ul className="cx-demo-copy-list"><li>Deterministic fictional lead IDs and vendor names.</li><li>Capture dates, sample lifecycle status and call-attempt counts.</li><li>Illustrative amounts stored as whole cents.</li></ul></section><section className="cx-demo-card"><header><h2>Not represented by this sample</h2></header><ul className="cx-demo-copy-list"><li>Live BigQuery access, freshness or reconciliation.</li><li>Approved releases, immutable evidence or identity permissions.</li><li>Real customer information, invoicing or bank collections.</li></ul></section></div></>}
        {current.path === '/settings' && <><section className="cx-demo-card cx-demo-configuration"><div className="cx-demo-config-icon"><FlaskConical size={30} aria-hidden="true" /></div><span className="cx-demo-eyebrow">Browser-only workspace</span><h2>A working preview, without touching your cloud</h2><p>The demo is isolated from live authentication and API providers. It uses a small, deterministic set of fictional records bundled with the application. No database connection is opened.</p><dl className="cx-demo-detail-list"><div><dt>Data source</dt><dd>Local synthetic fixture</dd></div><div><dt>Scenario</dt><dd>{DEMO_SCENARIO.name}</dd></div><div><dt>Sample period</dt><dd>1–31 July 2026 · UTC</dd></div><div><dt>Sample size</dt><dd>{number(DEMO_LEADS.length)} fictional leads</dd></div><div><dt>Currency</dt><dd>ZAR · illustrative only</dd></div><div><dt>Google Cloud changes</dt><dd>None</dd></div></dl></section><section className="cx-demo-card"><header><div><h2>When you open live mode</h2><p>Live access still requires the configured identity gateway and permission to read the selected workspace.</p></div></header><p className="cx-demo-configuration-copy">This demonstration does not sign you in, grant a role, configure credentials or make a live connection appear healthy. Live mode keeps its normal access checks. Opening it reloads the app and leaves this demo state behind.</p><a className="cx-button-primary" href={LIVE_ENTRY_URL}>Open live mode <ArrowRight size={16} aria-hidden="true" /></a></section></>}
        <footer className="cx-demo-footer"><span><FlaskConical size={14} aria-hidden="true" />{DEMO_SCENARIO.name} · all records are fictional</span><span>No live API or Google Cloud connection</span></footer>
      </main>
    </div>
    <Modal open={selected !== null} onClose={() => setSelected(null)} label={selected ? `Synthetic demo lead ${selected.id}` : 'Synthetic demo lead'} className="cx-demo-modal">{selected && <><header><div><span className="cx-demo-eyebrow">Synthetic record · not a real person</span><h2>{selected.id}</h2></div><button className="cx-icon-button" type="button" aria-label="Close sample details" onClick={() => setSelected(null)}><X size={20} /></button></header><p className="cx-demo-modal-note">This sample is generated locally for demonstration. It is not read from Google Cloud.</p><dl className="cx-demo-detail-list">{[['Vendor', selected.vendor], ['Source', selected.source], ['Lifecycle status', selected.status], ['Captured at · UTC', new Date(selected.capturedAt).toISOString().replace('T', ' ').replace('.000Z', '')], ['Call attempts', number(selected.callAttempts)], ['First dial', selected.firstDialMinutes === null ? 'Not recorded' : `${selected.firstDialMinutes} minutes`], ['Illustrative value', money(selected.revenueCents)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button className="cx-button-primary" type="button" onClick={() => setSelected(null)}>Return to demo</button></>}</Modal>
  </div>;
}

export default function DemoWorkspace() {
  return <BrowserRouter><DemoContent /></BrowserRouter>;
}
